<a href="https://colab.research.google.com/github/maulana0795/tugas-pengenalan-pola-M.-Iqbal-Maulana-G6501231052/blob/main/PolaHMM05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

pip install hmmlearn==0.2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.4/146.4 kB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for hmmlearn: filename=hmmlearn-0.2.2-cp310-cp310-linux_x86_64.whl size=465409 sha256=b659c3e8771c8895b141919784c9062d535fe2f985fd8bebd8d6f0f3c47a6c89
  Stored in directory: /root/.cache/pip/wheels/50/ce/de/18a9f86c6f0c2863350674635b19f0b5149eaa89f6c571dc06
Successfully built hmmlearn


In [2]:

states = ('Rainy', 'Sunny')
observations = ('walk', 'shop', 'clean')
start_probability = {'Rainy': 0.6, 'Sunny': 0.4}

transition_probability = {
   'Rainy' : {'Rainy': 0.7, 'Sunny': 0.3},
   'Sunny' : {'Rainy': 0.4, 'Sunny': 0.6},
   }

emission_probability = {
   'Rainy' : {'walk': 0.1, 'shop': 0.4, 'clean': 0.5},
   'Sunny' : {'walk': 0.6, 'shop': 0.3, 'clean': 0.1},
   }

In [3]:
from hmmlearn import hmm
import numpy as np

model = hmm.MultinomialHMM(n_components=2)
model.startprob_ = np.array([0.6, 0.4])
model.transmat_ = np.array([[0.7, 0.3],
                            [0.4, 0.6]])
model.emissionprob_ = np.array([[0.1, 0.4, 0.5],
                                [0.6, 0.3, 0.1]])


In [4]:
import math
math.exp(model.score(np.array([[0]])))

0.30000000000000004

In [5]:
math.exp(model.score(np.array([[1]])))

0.36000000000000004

In [6]:
math.exp(model.score(np.array([[2]])))

0.3400000000000001

In [7]:
math.exp(model.score(np.array([[2,2]])))

0.1244

In [8]:
logprob, seq = model.decode(np.array([[1,2,0]]).transpose())
print(math.exp(logprob))
print(seq)

0.015120000000000003
[0 0 1]


In [9]:
logprob, seq = model.decode(np.array([[2,2,2]]).transpose())
print(math.exp(logprob))
print(seq)

0.03674999999999999
[0 0 0]


In [10]:
math.exp(model.score(np.array([[2,2,0,0,1]])))

0.004082395400000001

In [11]:
logprob, seq = model.decode(np.array([[2,2,0,0,1]]).transpose())
print(math.exp(logprob))
print(seq)

0.001224720000000001
[0 0 1 1 1]
